### ISSUE TITLE
Fallback on a runtime check

### ISSUE THREAD

**Issue by gneuvill** [derive4j/hkt#12]
Since an annotation processor can be deactivated at compile time, it seems desirable to have at our disposal a fallback mechanism that would apply the very same logic as the one of the processor at runtime ; ideally, and in java terms, this should even happen at class loading time.

This would necessitates : 
- to abstract over the underlying api (`javax.lang.model` or `java.lang.reflect`)
- to automatically activate some code at class loading time : I've currently no idea how to do that (if that is even possible...)

**Comment by jbgi** [comment]
I think we should stay out of the run time business. Runtime checks will probably be partial or blow-up in the face of the user, given the complexity and diversity of java class-loading mechanisms.

**Comment by gneuvill** [comment]
Yep. Should I close ?
