### ISSUE TITLE
Annotation processor incorrectly ignore implementation of __ alias interfaces

### ISSUE THREAD

**Issue by jbgi** [derive4j/hkt#24]
release 0.9 ignore HK encoded classe that inherit from derive4j hkt interface through an alias interface.
Eg. nothing is generated for: 
```java
class HkTest<A> implements HigherKind1<HkTest<?>, A> {}

interface HigherKind1<TC extends HigherKind1<TC, ?>, T> extends __<TC, T> {}
```
(was testing how the encoding could be used in javaslang)

**Comment by gneuvill** [comment]
I don't understand : care to elaborate ?

**Comment by jbgi** [comment]
@gneuvill yep, my original description was also wrong. fixed now.
