### ISSUE TITLE
Support for types where some type parameters actually refer to mu-interface type parameters

### ISSUE THREAD

**Issue by DanielGronau** [derive4j/hkt#25]
Consider the Compose type from https://hackage.haskell.org/package/transformers-0.4.3.0/docs/Data-Functor-Compose.html

It is defined as `newtype Compose f g a = Compose { getCompose :: f (g a) }`, and allows to treat nested types like "List of Maybe" as a single HKT.

I tried to translate it straight-forward to:

```java
package org.highj.data.structural;

import org.derive4j.hkt.__;

public class Compose<F,G,A> implements __<Compose.µ<F,G>,A> {

    public interface µ<F,G>{}

    public Compose(__<F, __<G, A>> value) {
        this.value = value;
    }

    private final __<F,__<G,A>> value;

    public __<F, __<G, A>> get() {
        return value;
    }

}
```

However, HTK complains:
`Error:(5, 8) java: org.derive4j.hkt.__ is not the correct interface to use.
  Given the number of type parameters, org.highj.data.structural.Compose should implements org.derive4j.hkt.__3<org.highj.data.structural.Compose.µ<F,G>, F, G, A>`.

Maybe I overlooked something, or there is another way to implement it, but I got stuck.

**Comment by clinuxrulz** [comment]
A gut feeling tells me ```public class Compose<F,G,A> implements __3<Compose.µ,F,G,A>``` is the way to go. <-- Our monad transformers use that style.

**Comment by jbgi** [comment]
as @clinuxrulz said (at least this is the only encoding allowed by hkt). But we need to fix the error message, as it should have been `...should implements org.derive4j.hkt.__3<org.highj.data.structural.Compose.µ, F, G, A>`

**Comment by DanielGronau** [comment]
Yes, you are right, I shouldn't code so late...
